### ISSUE TITLE
Error building: Unable to handle event "click". HTML element is not nested within a component.

### ISSUE THREAD

**Issue by basickarl** [marko-js-samples/marko-widgets-client-rendering#2]
node v7.7.4
npm v4.1.2

Hi! I get the following error when building:
```
karl@karl-Dell-Precision-M3800:~/dev/node/marko-widgets-client-rendering(master)$ npm run build

> marko-widgets-client-rendering@1.0.0 build /home/karl/dev/node/marko-widgets-client-rendering
> lasso --main src/client.js --inject-into index.html --config lasso-config.json

Config:
{
    "outputDir": "/home/karl/dev/node/marko-widgets-client-rendering/static",
    "urlPrefix": "./static",
    "minify": false,
    "bundlingEnabled": false,
    "fingerprintsEnabled": false,
    "plugins": [
        "lasso-marko"
    ]
}

Optimizing page "index"...

WARNING!!
The "<var>" tag is deprecated. Please use "$ <js_code>" for JavaScript in the template. See: https://github.com/marko-js/marko/wiki/Deprecation:-var-assign-invoke-tags
  at src/components/number-spinner/index.marko:33:0

Failed to lasso page "index"! Reason: Error: Failed to walk dependency [require: ./components/number-spinner]. Dependency chain: [require: /home/karl/dev/node/marko-widgets-client-rendering/src/client.js] → [require: ./components/number-spinner]. Cause: Error: An error occurred while trying to compile template at path "/home/karl/dev/node/marko-widgets-client-rendering/src/components/number-spinner/index.marko". Error(s) in template:
1) [src/components/number-spinner/index.marko:37:4] Unable to handle event "click". HTML element is not nested within a component.
2) [src/components/number-spinner/index.marko:41:4] Unable to handle event "keyup". HTML element is not nested within a component.
3) [src/components/number-spinner/index.marko:44:4] Unable to handle event "click". HTML element is not nested within a component.

    at module.exports (/home/karl/dev/node/marko-widgets-client-rendering/node_modules/raptor-util/createError.js:7:50)
    at AsyncValue.<anonymous> (/home/karl/dev/node/marko-widgets-client-rendering/node_modules/lasso/lib/dependency-walker.js:141:48)
    at notifyCallbacks (/home/karl/dev/node/marko-widgets-client-rendering/node_modules/raptor-async/AsyncValue.js:76:35)
    at AsyncValue.reject (/home/karl/dev/node/marko-widgets-client-rendering/node_modules/raptor-async/AsyncValue.js:240:9)
    at getDependenciesCallback (/home/karl/dev/node/marko-widgets-client-rendering/node_modules/lasso/lib/dependencies/Dependency.js:361:47)
    at runMicrotasksCallback (internal/process/next_tick.js:64:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Caused by: Error: An error occurred while trying to compile template at path "/home/karl/dev/node/marko-widgets-client-rendering/src/components/number-spinner/index.marko". Error(s) in template:
1) [src/components/number-spinner/index.marko:37:4] Unable to handle event "click". HTML element is not nested within a component.
2) [src/components/number-spinner/index.marko:41:4] Unable to handle event "keyup". HTML element is not nested within a component.
3) [src/components/number-spinner/index.marko:44:4] Unable to handle event "click". HTML element is not nested within a component.

    at handleErrors (/home/karl/dev/node/marko-widgets-client-rendering/node_modules/marko/compiler/Compiler.js:82:21)
    at Compiler.compile (/home/karl/dev/node/marko-widgets-client-rendering/node_modules/marko/compiler/Compiler.js:160:9)
    at _compile (/home/karl/dev/node/marko-widgets-client-rendering/node_modules/marko/compiler/index.js:89:33)
    at compileFile (/home/karl/dev/node/marko-widgets-client-rendering/node_modules/marko/compiler/index.js:136:16)
    at Object.compileFileForBrowser (/home/karl/dev/node/marko-widgets-client-rendering/node_modules/marko/compiler/index.js:147:12)
    at Object.init (/home/karl/dev/node/marko-widgets-client-rendering/node_modules/lasso-marko/lasso-marko-plugin.js:40:52)
    at Promise (/home/karl/dev/node/marko-widgets-client-rendering/node_modules/lasso/lib/dependencies/RequireHandler.js:38:40)
    at RequireHandler.init (/home/karl/dev/node/marko-widgets-client-rendering/node_modules/lasso/lib/dependencies/RequireHandler.js:36:16)
    at Ctor.getDependencies (/home/karl/dev/node/marko-widgets-client-rendering/node_modules/lasso-require/src/dep-require.js:372:35)
    at Ctor.getPackageManifest (/home/karl/dev/node/marko-widgets-client-rendering/node_modules/lasso/lib/dependencies/Dependency.js:376:44)
------------------------------------
1 page(s) failed to build

npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/home/karl/.nvm/versions/node/v7.7.4/bin/node" "/home/karl/.nvm/versions/node/v7.7.4/bin/npm" "run" "build"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! marko-widgets-client-rendering@1.0.0 build: `lasso --main src/client.js --inject-into index.html --config lasso-config.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the marko-widgets-client-rendering@1.0.0 build script 'lasso --main src/client.js --inject-into index.html --config lasso-config.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the marko-widgets-client-rendering package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lasso --main src/client.js --inject-into index.html --config lasso-config.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs marko-widgets-client-rendering
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls marko-widgets-client-rendering
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/karl/dev/node/marko-widgets-client-rendering/npm-debug.log
```

**Comment by basickarl** [comment]
Made it work with the following:

```
import './style.css'

class {
    onInput(input) {
        var value = input.value || 0;

        this.state = {
            value: value
        };
    }

    handleIncrementClick (delta) {
        this.state.value += delta;
    }
    handleInputKeyUp (event, el) {
        var newValue = el.value;
        if (/^-?[0-9]+$/.test(newValue)) {
            this.state.value = parseInt(newValue, 10);
        }
    }
};

$ var value=state.value

<span>

    <button type="button" onClick("handleIncrementClick", -1)>
        -
    </button>

    <input type="text" value=state.value size="6"
        onKeyUp("handleInputKeyUp")>

    <button type="button" onClick("handleIncrementClick", 1)>
        +
    </button>

</span>
```

**Comment by austinkelleher** [comment]
Fixed in https://github.com/marko-js-samples/marko-client-rendering/commit/a7ee049e1cb95da646e7203786820e2ea923ab22
